[tool.black]
line-length = 90
include = '''

(
    (
        {{cookiecutter.plugin_package}}
      | tests
      | .github
    ).*\.pyi?$
)|(
    setup\.py
)
'''
exclude = '''

(
    # we want to still be able to apply patches from upstream w/o match issues
    {{cookiecutter.plugin_package}}/vendor
)
'''
